#pragma once

#include "util.hpp"
#include <Eigen/Sparse>
#include <Eigen/SparseLU>



struct constr : public poly<cplx>{//this is temporary for now
	void update(const std::vector<cplx> &in, cplx &val, std::vector<cplx> &dir){evalValAndDir(in, val, dir);}
};


struct state{
	int n, numvars;
	std::vector<cplx> vars;
	std::vector<bool> fixed;

	std::vector<std::vector<int>> constrOpNums;//must be in increasing order or it will break Eigen

	std::vector<cplx> constrVal;
	std::vector<std::vector<cplx>> constrDir;

	std::vector<constr> constrs;

	void rsNumvars(int Numvars){
		numvars = Numvars;
		vars.resize(numvars);
		fixed.resize(numvars);
		return;
	}

	void rsN(int N){
		n = N;
		constrOpNums.resize(n);
		constrVal.resize(n);
		constrDir.resize(n);
		constrs.resize(n);
		return;
	}

	void updateVals(){//temp
		for(int i = 0; i < n; i++){
			std::vector<cplx> val(constrOpNums[i].size());
			for(int j = 0; j < constrOpNums[i].size(); j++) val[j] = vars[constrOpNums[i][j]];

			constrs[i].update(val, constrVal[i], constrDir[i]);
		}
	}
};//any changes to state other then to vars requires regenerating the decent engine



struct decentEngine{
	state& S;

	std::vector<int> renamed;

	std::vector<cplx> nzval;
	std::vector<int> colind;
	std::vector<int> rowptr;

	std::vector<cplx> b_vals;
	std::vector<cplx> x_vals;

	std::unique_ptr<Eigen::Map<Eigen::SparseMatrix<cplx, Eigen::ColMajor>>> A_Trans;//this is a ptr to a constructor of a Sparse Matrix with nzval, colind, rowptr, so essentially it is a reference to the Matrix that would be generated by those

	Eigen::SparseLU<Eigen::SparseMatrix<cplx, Eigen::ColMajor>, Eigen::COLAMDOrdering<int>> solver;

	std::mt19937 gen;

	decentEngine(state &s);

	double update();

	void regen();//regenerates engine

	void addNoise(std::uniform_real_distribution<double> db);

	void addNoise(double db);//10^18 db hehe

	int descend();
};



int testing(std::istream& in);