#include "util.cpp"
#include <Eigen/Sparse>
#include <Eigen/SparseLU>

using namespace std;
/*
testing:

https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,source:'//+Type+your+code+here,+or+load+an+example.%0Aint+square(int+num)+%7B%0A++++return+num+*+num%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:executor,i:(argsPanelShown:'0',compilationPanelShown:'0',compiler:g162,compilerName:'',compilerOutShown:'0',execArgs:'',execStdin:'',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'',overrides:!(),runtimeTools:!((name:heaptrack,options:!((name:graph,value:yes)))),source:1,stdinPanelShown:'0',wrap:'1'),l:'5',n:'0',o:'Executor+x86-64+gcc+16.2+(C%2B%2B,+Editor+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4
*/




struct constr : public poly<cplx>{//this is temporary
	void update(const vector<cplx> &in, cplx &val, vector<cplx> &dir){evalValAndDir(in, val, dir);}
};


struct state{
	int n, numvars;
	vector<cplx> vars;
	vector<bool> fixed;

	vector<vector<int>> constrOpNums;//must be in increasing order or it will break Eigen

	vector<cplx> constrVal;
	vector<vector<cplx>> constrDir;

	vector<constr> constrs;

	void rsNumvars(int Numvars){
		numvars = Numvars;
		vars.resize(numvars);
		fixed.resize(numvars);
		return;
	}

	void rsN(int N){
		n = N;
		constrOpNums.resize(n);
		constrVal.resize(n);
		constrDir.resize(n);
		constrs.resize(n);
		return;
	}

	void updateVals(){//temp
		for(int i = 0; i < n; i++){
			vector<cplx> val(constrOpNums[i].size());
			for(int j = 0; j < constrOpNums[i].size(); j++) val[j] = vars[constrOpNums[i][j]];

			constrs[i].update(val, constrVal[i], constrDir[i]);
		}
	}
};//any changes to state other then to vars requires regenerating the decent engine



struct decentEngine{
	state& S;

	vector<int> renamed;

	vector<cplx> nzval;
	vector<int> colind;
	vector<int> rowptr;

	vector<cplx> b_vals;
	vector<cplx> x_vals;

	unique_ptr<Eigen::Map<Eigen::SparseMatrix<cplx, Eigen::ColMajor>>> A_Trans;//this is a ptr to a constructor of a Sparse Matrix with nzval, colind, rowptr, so essentially it is a reference to the Matrix that would be generated by those

	Eigen::SparseLU<Eigen::SparseMatrix<cplx, Eigen::ColMajor>, Eigen::COLAMDOrdering<int>> solver;

	mt19937 gen;

	decentEngine(state &s) : S(s){
		gen.seed(rd());
	}

	~decentEngine() = default;


	double update(){
		S.updateVals();

		double maxdist = 0;

		int cnt = 0;
		for(int coni = 0; coni < S.n; coni++){
			b_vals[coni] = -S.constrVal[coni];

			maxdist = max(maxdist, abs(S.constrVal[coni]));

			for(int i = 0; i < S.constrOpNums[coni].size(); i++){
				if(!S.fixed[S.constrOpNums[coni][i]]) nzval[cnt++] = S.constrDir[coni][i];
			}
		}

		return maxdist;
	}

	void regen(){
		renamed.resize(S.numvars, -1); int unfixed = 0;
		for(int i = 0; i < S.numvars; i++){
			if(!S.fixed[i]) renamed[i] = unfixed++;
		}

		b_vals.resize(S.n);
		x_vals.resize(S.n);

		int nnz = 0;
		rowptr.resize(S.n+1); rowptr[0] = 0;
		for(int coni = 0; coni < S.n; coni++){
			for(auto &opnum : S.constrOpNums[coni]){
				if(renamed[opnum] != -1){
					colind.push_back(renamed[opnum]);
					nnz++;
				}
			}
			rowptr[coni+1] = nnz;
		}

		nzval.resize(nnz);

		A_Trans = make_unique<Eigen::Map<Eigen::SparseMatrix<cplx, Eigen::ColMajor>>>(S.n, S.n, nnz, rowptr.data(), colind.data(), nzval.data());

		solver.setPivotThreshold(1.0);
		solver.analyzePattern(*A_Trans);
	}

	void addNoise(uniform_real_distribution<double> db){
		for(int i = 0; i < S.numvars; i++){
			if(!S.fixed[i]) S.vars[i] += cplx(db(gen), db(gen));
		}

		return;
	}

	void addNoise(double db){//10^18 db hehe
		return addNoise(uniform_real_distribution<double>(-db, db));
	}

	int descend(){
		solver.factorize(*A_Trans);
		if(solver.info() != Eigen::Success){
			cerr << "Solver failed: " << solver.info() << "\n" << flush;
			cerr << "n: " << S.n << "\ncolind: " << colind << "\nrowptr: " << rowptr << "\nnzval: " << nzval << "\n" << flush;
			return solver.info();
		}
		
		Eigen::Map<Eigen::VectorXcd>(x_vals.data(), x_vals.size()) = solver.transpose().solve(Eigen::Map<Eigen::VectorXcd>(b_vals.data(), b_vals.size()));

		for(int i = 0; i < S.numvars; i++){
			if(renamed[i] != -1) S.vars[i] += x_vals[renamed[i]];
		}

		for(int i = 0; i < S.numvars; i++){
			if(abs(S.vars[i].imag()) < 1e-30) S.vars[i].imag(0);
		}

		return Eigen::Success;
	}
};











int main(){
	cin.tie(0);
	state S;

	string ignored;
	cin >> ignored >> ignored;
	int Numvars; cin >> ignored >> Numvars; S.rsNumvars(Numvars);
	
	cin >> ignored;
	numbering<string> vars;
	for(int i = 0; i < S.numvars; i++){
		string str; cin >> str; vars(str);
	}

	cin >> ignored;
	for(auto &x : S.vars) cin >> x;
	cin >> ignored;
	for(int i = 0; i < S.numvars; i++){int a; cin >> a; S.fixed[i] = a;}

	int N; cin >> ignored >> N; S.rsN(N);
	
	for(int i = 0; i < S.n; i++){
		vector<pair<cplx, vector<pair<int, int>>>> polynom;
		cplx coeff = 1;
		vector<pair<int, int>> terms;
		
		string str; cin >> ignored >> str;
		while(true){
			if(str == "POLY" || str == "DONE") break;
			if(str == "+"){cin >> str; continue;}
			if(str == "-"){cin >> str; coeff *= -1; continue;}
			
			if(!isalpha(str[0])){
				coeff *= stod(str);
				cin >> str;
			}
			else{
				coeff *= 1;
			}

			while(str != "+" && str != "-" && str != "POLY" && str != "DONE"){
				int currvar = vars[str];
				if(currvar == -1){
					cerr << "Reading state failed, variable not found: " << str << "\n" << flush;
				}
				int currpow = 1;
				cin >> str;
				if(str == "^") cin >> currpow >> str;

				S.constrOpNums[i].push_back(currvar);

				terms.push_back({currvar, currpow});
			}

			polynom.push_back({coeff, terms});
			coeff = 1;
			terms.clear();
		}

		sort(S.constrOpNums[i].begin(), S.constrOpNums[i].end());
		S.constrOpNums[i].erase(unique(S.constrOpNums[i].begin(), S.constrOpNums[i].end()), S.constrOpNums[i].end());

		S.constrDir[i].resize(S.constrOpNums[i].size());

		vector<int> invOpNum(S.numvars, -1);

		for(int j = 0; j < S.constrOpNums[i].size(); j++) invOpNum[S.constrOpNums[i][j]] = j;

		S.constrs[i].numvars = S.constrOpNums[i].size();
		for(auto &[coeff, terms] : polynom){
			vector<int> pexpo(S.constrOpNums[i].size());
			for(auto &[varnum, expo] : terms) pexpo[invOpNum[varnum]] = expo;
			S.constrs[i].P.push_back({coeff, pexpo});
		}
	}


	decentEngine D(S);
	D.regen();

	while(true){
		string str;
		cin >> str;
		if(str == ">"){}
		else if(str == "//") getline(cin, str);
		else if(str == "exit") break;
		else if(str == "run"){
			D.addNoise(1e-25);
			double diff = D.update();

			cout << "Diff: " << diff << "\n";

			if(D.descend() != Eigen::Success) return 1;
			
			cout << "Change: " << D.x_vals << "\n";
		}
		else if(str == "runn"){
			int n; cin >> n;
			while(n--){
				D.addNoise(1e-25);
				double diff = D.update();

				cout << "Diff: " << diff << "\n";

				if(D.descend() != Eigen::Success) return 1;

				cout << "Change: " << D.x_vals << "\n";

				if(diff < 1e-15){
					cout << "diff small exiting early" << "\n";
					break;
				}
			}
		}
		else if(str == "query"){
			cout << "Vars: " << S.vars << "\n";
			cout << "constrVals: " << S.constrVal << "\n";
		}
		else if(str == "modify"){
			string i; cin >> i;
			cin >> S.vars[vars[i]];
		}
		else{}
	}

	return 0;
}





/*
colinear(6)
dist()





*/






