#ifndef GEORG_SRC_HOLOMORPHENGINE_HPP_
#define GEORG_SRC_HOLOMORPHENGINE_HPP_

#include "util.hpp"
#include <Eigen/Sparse>
#include <Eigen/SparseLU>
#include "expression.cpp"


struct State{
	int n = 0, numvars = 0;
	std::vector<cplx> vars;
	std::vector<bool> fixed;

	std::vector<expression> constrs;

	cplx currval;//where the value goes
	std::vector<cplx> currdir;//must be of size big enough to handle all dirivitives being in here

	void rsNumvars(int Numvars);

	void add(expression C);

	void update(int i);

	void clear();
};//any changes to state other then to vars requires regenerating the decent engine


struct decentEngine : public State{
	std::vector<int> renamed;

	std::vector<cplx> nzval;
	std::vector<int> colind;
	std::vector<int> rowptr;

	std::vector<cplx> b_vals;
	std::vector<cplx> x_vals;

	std::unique_ptr<Eigen::Map<Eigen::SparseMatrix<cplx, Eigen::ColMajor>>> A_Trans;//this is a ptr to a constructor of a Sparse Matrix with nzval, colind, rowptr, so essentially it is a reference to the Matrix that would be generated by those

	Eigen::SparseLU<Eigen::SparseMatrix<cplx, Eigen::ColMajor>, Eigen::COLAMDOrdering<int>> solver;

	std::mt19937 gen;

	decentEngine();

	double update();

	void regen();//regenerates engine

	void addNoise(std::uniform_real_distribution<double> db);

	void addNoise(double db);//10^18 db hehe

	int descend();
};




while(n--){//add this to Georg Engine
	D.addNoise(1e-25);//make randomness scale with diff -> put this loops in engine
	double diff = D.update();

	Log << "Diff: " << diff << "\n";

	if(D.descend() != Eigen::Success) return 1;

	Log << "Change: " << D.x_vals << "\n";

	if(diff < 1e-15){
		Log << "diff small exiting early" << "\n";
		break;
	}
}

#endif // GEORG_SRC_HOLOMORPHENGINE_HPP_